services:
  - type: web
    name: vs-louvor-avida
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: GOOGLE_DRIVE_API_KEY
        sync: false
